### ISSUE TITLE
When a non-Pro user looks at the app page they see the pro experience

### ISSUE THREAD

**Issue by LimeyJohnson** [erikdkennedy/hurleyisms#16]
This is because the class .is-logged-in is used to denote both a logged in user and a pro user. I have created another class .is-pro to denote whether or not to show pro features. 

I have circlied the UI items that need to be pro vs just logged in
![image](https://cloud.githubusercontent.com/assets/845860/17381073/0bd6a292-597f-11e6-9a29-ccf8043a7d8a.png)
![image](https://cloud.githubusercontent.com/assets/845860/17381106/2aa2804c-597f-11e6-9a01-e66cb4a85ce2.png)

**Comment by erikdkennedy** [comment]
we already have a body class called .has-payment-error that corresponds with .if-payment-error for the individual item that needs to be shown/hidden.  will that work?
